apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis-deployment
  labels:
    app: sentiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment
  template:
    metadata:
      labels:
        app: sentiment
    spec:
      containers:
      - name: base-sentiment-analysis
        image: rkaushik302/sentiment-analysis:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: sentiment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30100